### ISSUE TITLE
ERR XML loader: Patching 'blocks.xml' from mod 'OcbClaimAutoRepair' failed

### ISSUE THREAD

**Issue by LennyPane** [OCB7D2D/OcbClaimAutoRepair#6]
Hello, building modpack for my server and found this error (same happening with OcbDensityHoe at least, I didn't removed other mods and decided to write here first)
![image](https://github.com/OCB7D2D/OcbClaimAutoRepair/assets/35034527/b03cbf66-fa30-4c42-a932-a0533bd0bd34)

Server Config with EAC disables for sure [(Pastebin)](https://pastebin.com/UtVyMh17)
Server log with detailed explanation about error [(Pastebin)](https://pastebin.com/VgA1rp59)

Thanks!

**Comment by mgreter** [comment]
The mod DLL isn't loaded, make sure it is uploaded correctly.
