### ISSUE TITLE
Ability to Change the Repair Speed

### ISSUE THREAD

**Issue by Eavilaswayce** [OCB7D2D/OcbClaimAutoRepair#8]
Do you think it would be possibility to create a variable that controls the repair speed? Something that is easily editable in a config file?
Thanks

**Comment by mgreter** [comment]
https://github.com/OCB7D2D/OcbClaimAutoRepair/blob/master/Config/blocks.xml#L27

**Comment by Eavilaswayce** [comment]
Thank you, I didn't think to look there. I checked your description and the only thing I saw was that 2000f was set internally so I thought that meant hard-coded. Thanks again!
