### ISSUE TITLE
Cosmetic rather then fuction issue

### ISSUE THREAD

**Issue by sphinxlady** [OCB7D2D/OcbClaimAutoRepair#9]
The green glow for the block being on and whats being repaired is larger then it should be.
Not sure if its v1 related or mod related.

![Untitled](https://github.com/user-attachments/assets/f478f080-80dd-4852-b945-4d93005f823c)

**Comment by sphinxlady** [comment]
V1.0(b336)

**Comment by mgreter** [comment]
Thxs for the patience with the issue.
Should be fixed with version 0.9.1.
